name: ChatFilter
version: 2.0.5
main: a4.papers.chatfilter.chatfilter.ChatFilter
api-version: 1.13
authors: [ A4_Papers ]
description: Basic Regex chat, book and anvil filter
commands:
  chatfilter:
    aliases: [cf]
    description: chatfilter
  clearchat:
    description: clear chat
